/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_loren_minesample_jniutil_JniUtil */

#ifndef _Included_com_example_loren_minesample_jniutil_JniUtil
#define _Included_com_example_loren_minesample_jniutil_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_loren_minesample_jniutil_JniUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_loren_minesample_jniutil_JniUtil_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
